########################################################################
# This is a reusable workflow
########################################################################
name: Opeepl Docker CI

on:
  workflow_call:
    inputs:
      image_name:        
        required: true
        type: string
      context:                
        type: string
      tag: 
        type: string
        default: latest
      region:
        type: string
        default: eu-west-1
      run_id: 
        type: string
    secrets:
      registry:
        required: true
      registry_access_key_id:
        required: true
      registry_secret_access_key:
        required: true

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Log into registry 
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.registry }}
          username: ${{ secrets.registry_access_key_id }}
          password: ${{ secrets.registry_secret_access_key }}
        env:
          AWS_REGION: ${{ inputs.region }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.registry }}/${{ inputs.image_name }}

      # Runs a single command using the runners shell
      - name: Build Docker Image
        id: build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ inputs.context }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}_${{ github.run_id }},${{ secrets.registry }}/${{ inputs.image_name }}:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
