name: Terraform Docs

on:
  workflow_call:
    inputs:
      runner-label:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  terraform-docs:    
    runs-on: ${{ inputs.runner-label }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Terraform Docs
      if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      uses: terraform-docs/gh-actions@v1.0.0
      with:
        find-dir: ./
        output-file: README.md
        output-method: inject
        git-push: "true"
    
    - name: Finalize Docs
      # if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
      run: |
        echo "# Current Modules" > README_MODULES.md
        
        for dir in `ls -d */`; 
        do
          FILE=${dir}README.md
          if test -f "$FILE"; then
              echo "* [${dir}](${FILE})" >> README_MODULES.md
          fi
        done;
        
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
